[project]
name = "mytestdjango-five-final"
version = "0.1.0"
description = "Django backend project for collaborative development."
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "asgiref==3.8.1",
    "attrs==24.2.0",
    "autobahn==24.4.2",
    "Automat==24.8.1",
    "blinker==1.9.0",
    "certifi==2024.8.30",
    "cffi==1.17.1",
    "channels==4.1.0",
    "channels_redis==4.2.1",
    "click==8.1.7",
    "colorama==0.4.6",
    "constantly==23.10.4",
    "consumers==0.6.1",
    "contourpy==1.3.1",
    "cryptography==43.0.3",
    "cycler==0.12.1",
    "daphne==4.1.2",
    "distlib==0.3.9",
    "Django==5.1.2",
    "django-cors-headers==4.5.0",
    "djangorestframework==3.15.2",
    "drf-yasg==1.21.8",
    "filelock==3.16.1",
    "flasgger==0.9.7.1",
    "Flask==3.1.0",
    "fonttools==4.56.0",
    "geographiclib==2.0",
    "geopy==2.4.1",
    "h11==0.14.0",
    "hyperlink==21.0.0",
    "idna==3.10",
    "incremental==24.7.2",
    "inflection==0.5.1",
    "itsdangerous==2.2.0",
    "Jinja2==3.1.4",
    "jsonschema==4.23.0",
    "jsonschema-specifications==2025.4.1",
    "kiwisolver==1.4.8",
    "MarkupSafe==3.0.2",
    "matplotlib==3.10.3",
    "mistune==3.1.3",
    "msgpack==1.1.1",
    "numpy==2.3.1",
    "packaging==25.0",
    "pillow==11.3.0",
    "psutil==7.0.0",
    "pyasn1==0.6.1",
    "pyasn1_modules==0.4.2",
    "pycparser==2.22",
    "pymap3d==3.1.0",
    "pyOpenSSL==25.1.0",
    "pyparsing==3.2.3",
    "python-dateutil==2.9.0.post0",
    "pytz==2025.2",
    "PyYAML==6.0.2",
    "redis==6.2.0",
    "referencing==0.36.2",
    "rpds-py==0.26.0",
    "service-identity==24.2.0",
    "setuptools==80.9.0",
    "sgp4==2.24",
    "six==1.17.0",
    "sqlparse==0.5.3",
    "Twisted==25.5.0",
    "txaio==25.6.1",
    "typing_extensions==4.14.0",
    "tzdata==2025.2",
    "uritemplate==4.2.0",
    "Werkzeug==3.1.3",
    "zope.interface==7.2",
]

[tool.uv]
package = false
