# Generated by Django 5.1.2 on 2025-06-30 07:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interfaceIp', models.GenericIPAddressField(blank=True, default=None, null=True, verbose_name='IP Address')),
                ('interfaceIndex', models.IntegerField(blank=True, default=None, null=True, verbose_name='Interface Index')),
                ('subnetMask', models.CharField(default=None, max_length=50, verbose_name='Subnet Mask')),
                ('is_default', models.BooleanField(default=True, verbose_name='Default Gateway')),
                ('is_allocated', models.BooleanField(default=False, verbose_name='IP Allocated')),
            ],
            options={
                'verbose_name': 'Network Interface',
                'verbose_name_plural': 'Network Interfaces',
                'ordering': ['node', 'interfaceIndex'],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeName', models.CharField(max_length=255)),
                ('nodeImage', models.CharField(max_length=255)),
                ('nodeType', models.CharField(choices=[('satellite', 'Satellite'), ('normalNode', 'Normal Node')], max_length=50)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('alt', models.FloatField(blank=True, null=True)),
                ('startTime', models.DateTimeField(blank=True, null=True)),
                ('eccentricity', models.FloatField(blank=True, null=True)),
                ('argPerigee', models.FloatField(blank=True, null=True)),
                ('inclination', models.FloatField(blank=True, null=True)),
                ('meanAnomaly', models.FloatField(blank=True, null=True)),
                ('meanMotion', models.FloatField(blank=True, null=True)),
                ('raan', models.FloatField(blank=True, null=True)),
                ('viaPoints', models.JSONField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NodeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('templateInfo', models.TextField()),
                ('templateName', models.CharField(max_length=255, unique=True)),
                ('templateType', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sceneName', models.CharField(max_length=100)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('simulationStep', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkName', models.CharField(max_length=255)),
                ('linkType', models.CharField(choices=[('有线', '有线'), ('无线', '无线')], max_length=50)),
                ('bandwidth', models.FloatField(verbose_name='带宽(Mbps)')),
                ('packet_header_size', models.IntegerField(verbose_name='包头大小(Byte)')),
                ('transmission_delay', models.FloatField(blank=True, null=True, verbose_name='传输延迟(ms)')),
                ('packet_loss_rate', models.FloatField(blank=True, null=True, verbose_name='丢包率(%)')),
                ('transmission_speed', models.FloatField(blank=True, null=True, verbose_name='传输速度(Mb/s)')),
                ('subnetIp', models.GenericIPAddressField()),
                ('subnetMask', models.CharField(max_length=50)),
                ('destinationInterface', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_link', to='api.interface')),
                ('sourceInterface', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_link', to='api.interface')),
                ('destinationNodeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_links', to='api.node')),
                ('sourceNodeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='api.node')),
                ('sceneId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scene')),
            ],
        ),
        migrations.CreateModel(
            name='MacLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macProtocol', models.CharField(choices=[('802.11', '802.11')], max_length=50)),
                ('shortPacketLimit', models.IntegerField(default=7)),
                ('longPacketLimit', models.IntegerField(default=4)),
                ('rtsThreshold', models.IntegerField(default=0)),
                ('macPropagationDelay', models.FloatField(default=1)),
                ('interface', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mac_layer', to='api.interface')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('networkProtocol', models.CharField(choices=[('IPv4', 'IPv4')], max_length=50)),
                ('ipv4Address', models.GenericIPAddressField()),
                ('ipv4SubnetMask', models.GenericIPAddressField()),
                ('ipFragmentationUnit', models.IntegerField(default=2048)),
                ('interface', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='network_layer', to='api.interface')),
            ],
        ),
        migrations.AddField(
            model_name='interface',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='api.node'),
        ),
        migrations.CreateModel(
            name='PhysicalLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radioType', models.CharField(choices=[('Abstract', 'Abstract'), ('802.11b', '802.11b')], max_length=50)),
                ('radioCoverageId', models.CharField(blank=True, max_length=50, null=True)),
                ('centerFrequency', models.FloatField(blank=True, null=True)),
                ('bandwidth', models.FloatField(blank=True, null=True)),
                ('dataRate', models.FloatField(blank=True, null=True)),
                ('transmitPower', models.FloatField(blank=True, null=True)),
                ('receiveSensitivity', models.FloatField(blank=True, null=True)),
                ('receiveThreshold', models.FloatField(blank=True, null=True)),
                ('antennaType', models.CharField(choices=[('Omnidirectional', 'Omnidirectional'), ('Patterned', 'Patterned')], max_length=50)),
                ('gain', models.FloatField(default=0.0)),
                ('height', models.FloatField(default=1.5)),
                ('efficiency', models.FloatField(default=0.8)),
                ('mismatchLoss', models.FloatField(default=0.3)),
                ('cableLoss', models.FloatField(default=0.0)),
                ('connectionLoss', models.FloatField(default=0.2)),
                ('azimuth', models.FloatField(default=0)),
                ('elevation', models.FloatField(default=0)),
                ('roll', models.FloatField(default=0)),
                ('patternType', models.CharField(blank=True, choices=[('Ascii2d', 'Ascii2d')], max_length=50, null=True)),
                ('patternNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('azimuthPatternFile', models.FileField(blank=True, null=True, upload_to='antenna/azimuth/')),
                ('elevationPatternFile', models.FileField(blank=True, null=True, upload_to='antenna/elevation/')),
                ('patternCoverageParameter', models.FloatField(blank=True, null=True)),
                ('azimuthResolution', models.FloatField(blank=True, null=True)),
                ('elevationResolution', models.FloatField(blank=True, null=True)),
                ('interface', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='physical_layer', to='api.interface')),
            ],
        ),
        migrations.CreateModel(
            name='RoutingProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routingProtocol', models.CharField(choices=[('Bellman Ford', 'Bellman Ford')], max_length=50)),
                ('enableMulticast', models.BooleanField(default=False)),
                ('enableHSRP', models.BooleanField(default=False)),
                ('interface', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='routing_protocol', to='api.interface')),
            ],
        ),
        migrations.CreateModel(
            name='NodeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mappingIp', models.GenericIPAddressField()),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='api.interface')),
                ('sceneId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='api.scene')),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='sceneId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='api.scene'),
        ),
        migrations.CreateModel(
            name='LinkError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('errorStartTime', models.DateTimeField(blank=True, default='2025-01-16T01:00:00+00:00', null=True)),
                ('errorEndTime', models.DateTimeField(blank=True, default='2025-01-16T01:00:00+00:00', null=True)),
                ('linkId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='api.link')),
                ('sceneId', models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='linkerrors', to='api.scene')),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('errorStartTime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('errorEndTime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('nodeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='api.node')),
                ('sceneId', models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='nodeerrors', to='api.scene')),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessType', models.CharField(choices=[('CBR', 'CBR'), ('FTP', 'FTP')], default='CBR', max_length=10)),
                ('businessName', models.CharField(max_length=255)),
                ('cbrStartTime', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('cbrEndTime', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('cbrSendInterval', models.IntegerField(blank=True, null=True, verbose_name='发送间隔')),
                ('cbrPacketSize', models.IntegerField(blank=True, null=True, verbose_name='发送包大小')),
                ('ftpStartTime', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('ftpPacketCount', models.IntegerField(blank=True, null=True, verbose_name='发送包的数量')),
                ('destinationNodeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_configurations', to='api.node')),
                ('sourceNodeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_configurations', to='api.node')),
                ('sceneId', models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='api.scene')),
            ],
        ),
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subnetName', models.CharField(max_length=255)),
                ('subnetIp', models.GenericIPAddressField()),
                ('subnetMask', models.GenericIPAddressField()),
                ('sceneId', models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='subnets', to='api.scene')),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='subnet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='api.subnet'),
        ),
        migrations.AddField(
            model_name='interface',
            name='subnet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='api.subnet'),
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together={('sceneId', 'nodeName')},
        ),
        migrations.AlterUniqueTogether(
            name='interface',
            unique_together={('node', 'interfaceIndex')},
        ),
    ]
