# Generated by Django 5.2.3 on 2025-06-30 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='packet_header_size',
            new_name='packetHeaderSize',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='packet_loss_rate',
            new_name='packetLossRate',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='transmission_delay',
            new_name='transmissionDelay',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='transmission_speed',
            new_name='transmissionSpeed',
        ),
    ]
