# Generated by Django 5.2.3 on 2025-07-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_packet_header_size_link_packetheadersize_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='interfaceType',
            field=models.CharField(choices=[('sub', 'Subnet Interface'), ('link', 'Link Interface')], default='sub', max_length=10, verbose_name='Interface Type'),
        ),
        migrations.AddField(
            model_name='subnet',
            name='subnetType',
            field=models.CharField(choices=[('sub', '子网（sub）'), ('link', '链路（link）')], default='sub', max_length=10, verbose_name='子网类型'),
        ),
    ]
