# Generated by Django 5.2.3 on 2025-07-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_interface_interfacetype_subnet_subnettype'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='detail',
            field=models.JSONField(default={'Application': {'EnableEmulatedFTP': 'Yes', 'EnableEmulatedHTTP': 'Yes', 'EnableEmulatedTELNET': 'Yes'}, 'Faults': {}, 'File': {'IPInputQueue': 'Yes', 'IPInputScheduler': 'No', 'IPOutputScheduler': 'No', 'IPOutputSchedulergraph': 'No', 'MAC': 'Yes', 'PHYRadio': 'Yes'}, 'MAC': {'ConfigureMACAddress': 'No', 'ConfigureMediaType': 'No', 'DatabaseControl': 'NONE', 'EnableLLC': 'No', 'EnablePromiscuousMode': 'No', 'LongPacketTransmitLimit': '4', 'MACPropagationDelay': '1', 'MACPropagationDelayTimeType': 'microSeconds', 'MACProtocol': '802.11', 'RTSThreshold': '0', 'SecurityProtocol': 'None', 'ShortPacketTransmitLimit': '7', 'SpecifyNetworkSecurityParameters': 'No', 'StationAssociationType': 'None', 'StopReceivingafterHeaderMode': 'No'}, 'Network': {'EnableARP': 'No', 'EnableDHCP': 'No', 'EnableDNS': 'No', 'EnableEavesdropping': 'No', 'EnableExplicitCongestionNotification': 'No', 'EnableIFFCertification': 'No', 'EnableMobileIP': 'No', 'IPFragmentationUnit': '2048', 'IPInputQueueSize': '150000', 'IPOutputQueueScheduler': 'StrictPriority', 'IPv4Address': '169.0.0.1', 'IPv4SubnetMask': '255.255.255.0', 'NetworkProtocol': 'IPv4', 'PacketDropProbability': '0.0', 'SpecifyPacketDelay': 'No', 'SpecifyPerHopBehaviorFile': 'No'}, 'Physical': {'AntennaCableLoss': '0.0', 'AntennaConnectionLoss': '0.2', 'AntennaEfficiency': '0.8', 'AntennaGain': '0.0', 'AntennaHeight': '1.5', 'AntennaMismatchLoss': '0.3', 'AntennaModel': 'Omnidirectional', 'AntennaOrientationAzimuth': '0', 'AntennaOrientationAzimuthSpeed': '0', 'AntennaOrientationElevation': '0', 'AntennaOrientationRoll': '0', 'ChannelIndexfor20MHz': '6', 'CountryCode': 'SpecifyWiFiCountryProfilesFileinScenarioPropertiesEditorSupplementalFiles', 'DataRata': '2Mbps', 'EnableAutoRateFallback': 'No', 'EnergyModel': 'None', 'FrequencyBand': '2.4GHz', 'ListenableChannel': 'Channel1', 'ListeningChannel': 'Channel1', 'NoiseFactor': '10.0', 'PacketReceptionModel': 'PHY802.11aReceptionModel', 'RadioOverlayID': '[Optional]', 'Radiotype': '802.11bRadio', 'ReceiveSensitivityat11Mbps': '-76.0', 'ReceiveSensitivityat1Mbps': '-82.0', 'ReceiveSensitivityat2Mbps': '-80.0', 'ReceiveSensitivityat55Mbps': '-78.0', 'SpecifyAntennaModelfromFile': 'No', 'Temperature': '290.0', 'TransmissionPowerat11Mbps': '15.0', 'TransmissionPowerat1Mbps': '15.0', 'TransmissionPowerat2Mbps': '15.0', 'TransmissionPowerat55Mbps': '15.0', 'UseLegacy80211bPHYValues': 'No'}, 'Routing': {'EnableHSRPProtocol': 'No', 'EnableMulticast': 'No', 'EnableMulticastSourceDiscoveryProtocol': 'No', 'RoutingProtocolIPv4': 'BellmanFord'}}, verbose_name='Interface Detail'),
        ),
    ]
