# Generated by Django 5.1.2 on 2025-07-25 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_interface_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='clientId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='http_clients', to='api.node', verbose_name='HTTP客户端节点'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='httpStartTime',
            field=models.FloatField(blank=True, null=True, verbose_name='HTTP开始时间（s）'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='httpThreshTime',
            field=models.FloatField(blank=True, null=True, verbose_name='HTTP阈值时间（s）'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='serverList',
            field=models.JSONField(blank=True, null=True, verbose_name='HTTP服务器节点列表（节点ID列表）'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='tgDurationTime',
            field=models.FloatField(blank=True, null=True, verbose_name='Traffic-Gen持续时间（s）'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='tgPacketSize',
            field=models.IntegerField(blank=True, null=True, verbose_name='Traffic-Gen包大小（Bytes）'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='tgSendInterval',
            field=models.FloatField(blank=True, null=True, verbose_name='Traffic-Gen发送间隔（s）'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='tgStartTime',
            field=models.FloatField(blank=True, null=True, verbose_name='Traffic-Gen开始时间（s）'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='businessType',
            field=models.CharField(choices=[('CBR', 'CBR'), ('FTP', 'FTP'), ('TRAFFIC-GEN', 'TRAFFIC-GEN'), ('HTTP', 'HTTP')], default='CBR', max_length=20),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='cbrEndTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='CBR结束时间'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='cbrPacketSize',
            field=models.IntegerField(blank=True, null=True, verbose_name='CBR包大小（Bytes）'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='cbrSendInterval',
            field=models.IntegerField(blank=True, null=True, verbose_name='CBR发送间隔（ms）'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='cbrStartTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='CBR开始时间'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='destinationNodeId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_configurations', to='api.node'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='ftpPacketCount',
            field=models.IntegerField(blank=True, null=True, verbose_name='FTP包数量'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='ftpStartTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='FTP开始时间'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='sourceNodeId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_configurations', to='api.node'),
        ),
    ]
