# Generated by Django 5.1.2 on 2025-08-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_configuration_clientid_configuration_httpstarttime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='TransferType',
            field=models.CharField(blank=True, default='ID', max_length=2, null=True),
        ),
    ]
