# Generated by Django 5.1.2 on 2025-08-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_configuration_transfertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='specialType',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='特殊节点类型'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='detail',
            field=models.JSONField(default={}, verbose_name='Interface Detail'),
        ),
    ]
