# Generated by Django 5.1.2 on 2025-08-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_node_specialtype_alter_interface_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='coordinateSystem',
            field=models.CharField(choices=[('CARTESIAN', 'Cartesian'), ('LATLONALT', 'LatLonAlt')], default='LATLONALT', max_length=20),
        ),
    ]
