# Generated by Django 5.1.2 on 2025-09-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_scene_coordinatesystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='linkConfig',
            field=models.BooleanField(default=True, verbose_name='链路是否启用配置'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='detail',
            field=models.JSONField(blank=True, default={}, null=True, verbose_name='Interface Detail'),
        ),
        migrations.AlterField(
            model_name='link',
            name='bandwidth',
            field=models.FloatField(blank=True, null=True, verbose_name='带宽(Mbps)'),
        ),
        migrations.AlterField(
            model_name='link',
            name='packetHeaderSize',
            field=models.IntegerField(blank=True, null=True, verbose_name='包头大小(Byte)'),
        ),
    ]
