# Generated by Django 5.1.2 on 2025-09-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_link_linkconfig_alter_interface_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='linkConfig',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='链路是否启用配置'),
        ),
    ]
