# Generated by Django 5.1.2 on 2025-09-15 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_link_linkconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_tables', to='api.scene')),
            ],
        ),
    ]
