# Generated by Django 5.1.2 on 2025-09-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_slottable'),
    ]

    operations = [
        migrations.AddField(
            model_name='subnet',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
