# Generated by Django 5.1.2 on 2026-04-09 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_subnet_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networklayer',
            name='interface',
        ),
        migrations.RemoveField(
            model_name='physicallayer',
            name='interface',
        ),
        migrations.RemoveField(
            model_name='routingprotocol',
            name='interface',
        ),
        migrations.DeleteModel(
            name='MacLayer',
        ),
        migrations.DeleteModel(
            name='NetworkLayer',
        ),
        migrations.DeleteModel(
            name='PhysicalLayer',
        ),
        migrations.DeleteModel(
            name='RoutingProtocol',
        ),
    ]
