# Generated by Django 5.1.2 on 2026-04-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_networklayer_interface_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='cbrPrecedence',
            field=models.IntegerField(blank=True, null=True, verbose_name='CBR优先级'),
        ),
    ]
