# Generated by Django 5.1.2 on 2026-04-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_configuration_cbrprecedence'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='epochTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='历元时间'),
        ),
        migrations.AddField(
            model_name='node',
            name='orbitAltitude',
            field=models.FloatField(blank=True, null=True, verbose_name='轨道高度'),
        ),
        migrations.AddField(
            model_name='node',
            name='orbitArgPerigee',
            field=models.FloatField(blank=True, null=True, verbose_name='近地点幅角'),
        ),
        migrations.AddField(
            model_name='node',
            name='orbitInclination',
            field=models.FloatField(blank=True, null=True, verbose_name='轨道倾角'),
        ),
        migrations.AddField(
            model_name='node',
            name='orbitMeanAnomaly',
            field=models.FloatField(blank=True, null=True, verbose_name='平近点角'),
        ),
        migrations.AddField(
            model_name='node',
            name='orbitRaan',
            field=models.FloatField(blank=True, null=True, verbose_name='升交点赤经'),
        ),
        migrations.AddField(
            model_name='node',
            name='orbitStepCount',
            field=models.IntegerField(blank=True, null=True, verbose_name='轨道计算步数'),
        ),
        migrations.AddField(
            model_name='node',
            name='orbitStepSize',
            field=models.FloatField(blank=True, null=True, verbose_name='轨道计算步长'),
        ),
    ]
