# Generated by Django 5.1.2 on 2026-04-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_node_epochtime_node_orbitaltitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='detail',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Interface Detail'),
        ),
    ]
