# Generated by Django 5.1.2 on 2026-04-16 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_interface_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='interfaceId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='api.interface', verbose_name='接口ID'),
        ),
        migrations.AddField(
            model_name='scene',
            name='channelConfigs',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='信道配置列表'),
        ),
        migrations.AddField(
            model_name='scene',
            name='channelCount',
            field=models.IntegerField(default=0, verbose_name='信道数量'),
        ),
    ]
