# Generated by Django 5.1.2 on 2026-04-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_error_interfaceid_scene_channelconfigs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='broadcastAppType',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='广播应用类型'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='broadcastDest',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='广播目的地址'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='broadcastFragmentNum',
            field=models.IntegerField(blank=True, null=True, verbose_name='广播分片数量'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='broadcastFragmentSize',
            field=models.IntegerField(blank=True, null=True, verbose_name='广播分片大小'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='broadcastInterval',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='广播发送间隔'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='broadcastLifeTime',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='广播生命周期'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='broadcastStartTime',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='广播启动时间'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='broadcastTransportType',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='广播传输类型'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='multicastDestination',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='组播目的地址'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='multicastEndTime',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='组播结束时间'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='multicastInterval',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='组播发送间隔'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='multicastItemSize',
            field=models.IntegerField(blank=True, null=True, verbose_name='组播单报文大小'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='multicastItemsToSend',
            field=models.IntegerField(blank=True, null=True, verbose_name='组播发送报文总数'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='multicastStartTime',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='组播启动时间'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='poissonEndTime',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='泊松分布结束时间'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='poissonMeanInterval',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='平均发包间隔'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='poissonPacketSize',
            field=models.IntegerField(blank=True, null=True, verbose_name='发送包大小'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='poissonStartTime',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='泊松分布开始时间'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='businessType',
            field=models.CharField(choices=[('CBR', 'CBR'), ('FTP', 'FTP'), ('TRAFFIC-GEN', 'TRAFFIC-GEN'), ('HTTP', 'HTTP'), ('泊松分布', '泊松分布'), ('广播业务', '广播业务'), ('组播业务', '组播业务')], default='CBR', max_length=20),
        ),
    ]
